# Example:
# --config benchmarks.yml --scenario proxy-yarp --profile aspnet-physical

imports:
  - https://raw.githubusercontent.com/aspnet/Benchmarks/master/src/BenchmarksDriver2/benchmarks.proxy.yml

variables:
  serverPort: 5000

jobs:
  yarp:
    source:
      repository: https://github.com/microsoft/reverse-proxy.git
      branchOrCommit: master
      project: samples/BenchmarkApp/BenchmarkApp.csproj
    readyStateText: Application started.
    arguments: '--urls {{serverUri}}:{{serverPort}} --clusterUrls {{downstreamUri}}'
    port: 5000

scenarios:
  proxy-yarp:
    downstream:
      job: downstream
    application:
      job: yarp
    load:
      job: bombardier
